'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,BrainCircuit,Check,ChevronRight,Heart,History,RefreshCw,Share2,Sparkles,UserRound,X,Zap} from 'lucide-react';
import type {Analysis,Gender} from '@/lib/types';

type Person={name:string;gender:Gender};
type Activity={runCount:number;popularNames:string[]};
const empty:Person={name:'',gender:'unspecified'};
const stages=['한글 이름의 획수를 세는 중…','음양의 균형을 확인하는 중…','발음오행의 흐름을 잇는 중…','메이저 아르카나를 섞는 중…','세 장의 카드를 펼치는 중…','이름과 타로를 함께 읽는 중…','결과를 정리하는 중…'];
const genders:[Gender,string][]=[['male','남성'],['female','여성'],['unspecified','선택 안 함']];

export default function Home(){
  const [a,setA]=useState<Person>(empty),[b,setB]=useState<Person>(empty),[view,setView]=useState<'home'|'loading'|'result'>('home'),[result,setResult]=useState<Analysis|null>(null),[stage,setStage]=useState(0),[error,setError]=useState(''),[activity,setActivity]=useState<Activity>({runCount:78,popularNames:[]}),logoTaps=useRef({count:0,last:0});
  async function analyze(){if(!a.name.trim()||!b.name.trim()){setError('두 사람의 이름을 모두 입력해 주세요.');return}setError('');setView('loading');setStage(0);const timer=setInterval(()=>setStage(s=>Math.min(s+1,6)),800),started=Date.now();try{const res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nameA:a.name,nameB:b.name,genderA:a.gender,genderB:b.gender})}),data=await res.json();if(!res.ok)throw new Error(data.error);if(data.activity)setActivity(data.activity);await new Promise(r=>setTimeout(r,Math.max(0,5000-(Date.now()-started))));setResult(data.result);setView('result')}catch(e){setError(e instanceof Error?e.message:'오류가 발생했어요.');setView('home')}finally{clearInterval(timer)}}
  const restart=()=>{setA(empty);setB(empty);setResult(null);setError('');setView('home');window.scrollTo({top:0,behavior:'smooth'})};
  const secretTap=()=>{const now=Date.now(),state=logoTaps.current;state.count=now-state.last>5000?1:state.count+1;state.last=now;if(state.count>=15){state.count=0;location.assign('/owner')}};
  useEffect(()=>{fetch('/api/analyze').then(r=>r.json()).then(d=>d.activity&&setActivity(d.activity)).catch(()=>{});const key=(e:KeyboardEvent)=>{if(e.altKey&&e.shiftKey&&(e.code==='KeyL'||e.key.toLowerCase()==='l')){e.preventDefault();location.assign('/owner')}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[]);
  if(view==='loading')return <Loading a={a.name} b={b.name} stage={stage}/>;
  if(view==='result'&&result)return <Result a={a.name} b={b.name} r={result} activity={activity} restart={restart}/>;
  return <div className="app"><Header runCount={activity.runCount} onSecretTap={secretTap}/><main className="home"><section className="intro"><h1>두 사람의 이름 궁합을<br/><span>확인해 보세요</span></h1><p>한글 이름의 획수·음양·발음오행을 계산하고 실제 타로 카드 3장과 함께 풀이해요.</p><div className="intro-spec"><span>NAME / FIVE ELEMENTS</span><span>3 CARD TAROT</span><span>2026</span></div></section><PersonCard label="PERSON A" tone="violet" value={a} onChange={setA}/><div className="merge"><Zap size={20}/><small>LINK</small></div><PersonCard label="PERSON B" tone="cyan" value={b} onChange={setB}/>{error&&<p className="error">{error}</p>}<button className="primary" onClick={analyze}><Sparkles/>분석 실행<ChevronRight/></button></main><Bottom/></div>;
}

function Header({runCount,onSecretTap}:{runCount:number;onSecretTap:()=>void}){return <header><button className="brand" aria-label="LAB 시스템" onClick={onSecretTap}><Sparkles/><span>LAB / R-24</span></button><div className="header-count" aria-label={`누적 궁합 열기 ${runCount}회`}><small>누적 궁합 열기</small><strong>{runCount}</strong><span>회</span></div></header>}
function PersonCard({label,tone,value,onChange}:{label:string;tone:string;value:Person;onChange:(v:Person)=>void}){return <section className={`person ${tone}`}><div className="module-id"><span>MODULE</span><b>{label}</b><small>{tone==='violet'?'CFG-204':'CFG-205'}</small></div><h2><UserRound/>{tone==='violet'?'첫 번째 사람':'두 번째 사람'}</h2><label>한글 이름<input maxLength={20} value={value.name} onChange={e=>onChange({...value,name:e.target.value})} placeholder="이름을 입력해 주세요"/></label><fieldset><legend>성별 <small>선택</small></legend><div>{genders.map(([v,l])=><button type="button" key={v} className={value.gender===v?'selected':''} onClick={()=>onChange({...value,gender:v})}>{value.gender===v&&<Check/>}{l}</button>)}</div></fieldset><p className="serial">ID {tone==='violet'?'17-A':'17-B'} / HANDLE WITH CARE</p></section>}
function Loading({a,b,stage}:{a:string;b:string;stage:number}){return <main className="loading"><span className="eyebrow">NAME & TAROT / READING</span><div className="orbit"><div className="orb orb-a">{[...a].slice(0,3).join('')}</div><div className="orb orb-b">{[...b].slice(0,3).join('')}</div><div className="core"><Sparkles/></div></div><h1>두 사람의 궁합을 보는 중</h1><p>{stages[stage]}</p><div className="progress"><i style={{width:`${Math.min(96,(stage+1)*14)}%`}}/></div><div className="stage-dots">{stages.map((_,i)=><span key={i} className={i<=stage?'on':''}/>)}</div><small>PROCESS {String(stage+1).padStart(2,'0')} / 07 · DO NOT CLOSE</small></main>}

const positive=(r:Analysis)=>[['금방 친해질 가능성',r.closenessPotential],['오래 편하게 지낼 가능성',r.relationshipStability],['말이 잘 통하는 정도',r.conversationCompatibility],['서로 신경 쓰는 정도',r.mutualAwareness],['같이 있을 때 편안함',r.comfortPotential]]as[string,number][];
const risks=(r:Analysis)=>[['처음에 어색할 수 있음',r.awkwardnessRisk],['서로 오해할 수 있음',r.misunderstandingRisk],['연락이 뜸해질 수 있음',r.communicationDropRisk],['다툴 수 있음',r.conflictRisk],['멀어질 수 있음',r.distancingRisk]]as[string,number][];
function Result({a,b,r,activity,restart}:{a:string;b:string;r:Analysis;activity:Activity;restart:()=>void}){
  const [shareStatus,setShareStatus]=useState('');
  const share=async()=>{const text=`${a} × ${b} 이름 궁합은 ${r.overallCompatibility}점!`;setShareStatus('');try{if(navigator.share){await navigator.share({title:'AI 이름 궁합',text});setShareStatus('공유가 완료되었습니다.')}else{await navigator.clipboard.writeText(text);setShareStatus('결과가 클립보드에 복사되었습니다.')}}catch(e){if(e instanceof DOMException&&e.name==='AbortError')setShareStatus('공유를 취소했습니다.');else setShareStatus('공유할 수 없습니다. 다시 시도해 주세요.')}};
  return <div className="app"><header><button onClick={restart} aria-label="처음으로 돌아가기"><ArrowLeft/></button><div className="brand"><Sparkles/><span>RESULT / R-24</span></div><div className="header-count"><small>누적 궁합 열기</small><strong>{activity.runCount}</strong><span>회</span></div></header><main className="results"><section className="score"><span className="eyebrow">NAME NUMEROLOGY × TAROT</span><div className="names"><b>{a}</b><X/><b>{b}</b></div><div className="gauge"><div><strong>{r.overallCompatibility}</strong><small>COMPATIBILITY / 100</small></div></div><h1>두 사람의 궁합</h1><p>{r.overallCompatibility>=80?'이름과 카드 모두 강한 끌림을 보여요':r.overallCompatibility>=65?'천천히 가까워질수록 좋은 사이예요':'서로의 다른 속도를 이해하는 게 중요해요'}</p><div className="result-spec"><span>NAME STROKES</span><span>FIVE ELEMENTS</span><span>3 CARD</span></div></section>
    <Card title="이름으로 계산한 궁합" icon={<BrainCircuit/>}><div className="name-reading-grid">{r.nameReadings.map(x=><article className="name-reading" key={x.name}><strong>{x.name}</strong><div><span>총획</span><b>{x.strokeTotal}획</b></div><div><span>수리</span><b>{x.number}</b></div><div><span>음양</span><b>음 {x.yin} · 양 {x.yang}</b></div><div><span>주된 오행</span><b>{x.primaryElement}</b></div><small>{x.elements.join(' · ')}</small></article>)}</div><p className="method-note">{r.nameMethod}</p></Card>
    <Card title="실제 카드로 본 두 사람" icon={<Sparkles/>}><div className="tarot-grid">{r.tarotCards.map(card=><article className="tarot-card" key={card.position}><img src={card.imageUrl} alt={`라이더-웨이트 ${card.name} 카드`}/><div><small>{card.position}</small><b>{card.name}</b><p>{card.meaning}</p></div></article>)}</div><p className="tarot-story">{r.summary}</p><p className="tarot-credit">Rider–Waite–Smith 카드 도판 · Wikimedia Commons</p></Card>
    <div className="metric-grid"><Metrics title="잘 맞는 정도" data={positive(r)} kind="good"/><Metrics title="조심할 신호" data={risks(r)} kind="risk"/></div><Card title="둘이 잘 맞는 점" icon={<Heart/>}><List items={r.positiveFactors}/></Card><Card title="이것만 조심해요" icon={<BrainCircuit/>}><List items={r.cautionFactors}/></Card><Card title="더 가까워지는 방법" icon={<Zap/>}><List items={r.relationshipAdvice}/></Card><Card title="요즘 자주 나온 이름" icon={<History/>}><p className="muted">{activity.popularNames.length?`${activity.popularNames.join(', ')} 이름은 요즘 자주 분석되고 있어요.`:'같은 이름이 3번 이상 나오면 여기에 표시돼요.'}</p></Card><div className="actions"><button className="primary" onClick={share}><Share2/>결과 공유</button><p className="action-status" aria-live="polite">{shareStatus}</p><button className="secondary" onClick={restart}><RefreshCw/>다른 이름으로 다시 하기</button></div></main><Bottom/></div>;
}
function List({items}:{items:string[]}){return <ul>{items.map(x=><li key={x}>{x}</li>)}</ul>}
function Card({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="card"><h2>{icon}{title}</h2>{children}</section>}
function Metrics({title,data,kind}:{title:string;data:[string,number][];kind:string}){return <section className={`card metrics ${kind}`}><h2>{title}</h2>{data.map(([l,v])=><div className="metric" key={l}><span>{l}<b>{v}%</b></span><i><em style={{width:`${v}%`}}/></i></div>)}</section>}
function Bottom(){return <div className="bottom" aria-label="현재 화면"><span className="active"><Heart/>분석</span><span><BrainCircuit/>AI ENGINE</span><span><History/>PRIVATE LOG</span></div>}
