import { randomInt } from 'node:crypto';
import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';

export const runtime = 'nodejs';
const input=z.object({nameA:z.string().trim().min(1).max(20).regex(/^[\p{L}\p{M}\s'-]+$/u),nameB:z.string().trim().min(1).max(20).regex(/^[\p{L}\p{M}\s'-]+$/u),genderA:z.enum(['male','female','unspecified']),genderB:z.enum(['male','female','unspecified'])});
const tarotCard=z.object({position:z.string(),name:z.string(),meaning:z.string(),imageUrl:z.string().url()});
const nameReading=z.object({name:z.string(),strokeTotal:z.number(),number:z.number(),yin:z.number(),yang:z.number(),primaryElement:z.string(),elements:z.array(z.string())});
const output=z.object({overallCompatibility:z.number().min(0).max(100),closenessPotential:z.number().min(0).max(100),relationshipStability:z.number().min(0).max(100),conversationCompatibility:z.number().min(0).max(100),mutualAwareness:z.number().min(0).max(100),comfortPotential:z.number().min(0).max(100),awkwardnessRisk:z.number().min(0).max(100),misunderstandingRisk:z.number().min(0).max(100),communicationDropRisk:z.number().min(0).max(100),conflictRisk:z.number().min(0).max(100),distancingRisk:z.number().min(0).max(100),summary:z.string().min(30).max(1000),tarotCards:z.array(tarotCard).length(3),nameReadings:z.array(nameReading).length(2),nameMethod:z.string(),positiveFactors:z.array(z.string()).length(3),cautionFactors:z.array(z.string()).length(3)});

const commons=(file:string)=>`https://commons.wikimedia.org/wiki/Special:Redirect/file/${file}`;
const deck=[
['바보','새로운 시작, 솔직한 호기심',72,'RWS_Tarot_00_Fool.jpg'],['마법사','먼저 다가가는 힘, 강한 표현력',84,'RWS_Tarot_01_Magician.jpg'],['여사제','말하지 않아도 느끼는 직감',78,'RWS_Tarot_02_High_Priestess.jpg'],['여황제','다정함, 편안한 애정',90,'RWS_Tarot_03_Empress.jpg'],['황제','안정감, 관계의 주도권',76,'RWS_Tarot_04_Emperor.jpg'],['교황','신뢰, 약속을 지키는 마음',82,'RWS_Tarot_05_Hierophant.jpg'],['연인','끌림, 중요한 선택',94,'RWS_Tarot_06_Lovers.jpg'],['전차','빠른 진전, 같은 목표',86,'RWS_Tarot_07_Chariot.jpg'],['힘','부드러운 인내, 감정 조절',88,'RWS_Tarot_08_Strength.jpg'],['은둔자','천천히 알아가는 시간',62,'RWS_Tarot_09_Hermit.jpg'],['운명의 수레바퀴','예상 밖의 만남과 변화',83,'RWS_Tarot_10_Wheel_of_Fortune.jpg'],['정의','솔직한 대화, 균형',80,'RWS_Tarot_11_Justice.jpg'],['매달린 사람','기다림, 관점 바꾸기',60,'RWS_Tarot_12_Hanged_Man.jpg'],['죽음','묵은 흐름의 끝과 새 출발',68,'RWS_Tarot_13_Death.jpg'],['절제','서로 다른 속도를 맞추는 힘',87,'RWS_Tarot_14_Temperance.jpg'],['악마','강한 끌림, 집착을 조심할 필요',65,'RWS_Tarot_15_Devil.jpg'],['탑','갑작스러운 감정 변화와 깨달음',55,'RWS_Tarot_16_Tower.jpg'],['별','기대, 오래 남는 설렘',92,'RWS_Tarot_17_Star.jpg'],['달','헷갈리는 신호, 깊은 감정',64,'RWS_Tarot_18_Moon.jpg'],['태양','함께 있을 때 커지는 밝은 에너지',96,'RWS_Tarot_19_Sun.jpg'],['심판','다시 이어지는 대화, 중요한 결론',81,'RWS_Tarot_20_Judgement.jpg'],['세계','잘 맞물리는 흐름, 완성감',95,'RWS_Tarot_21_World.jpg']] as const;
const positions=['지금 두 사람의 흐름','서로 끌리는 이유','앞으로의 방향'];
function drawTarot(){const pool=[...deck];return positions.map(position=>{const [name,meaning,energy,file]=pool.splice(randomInt(pool.length),1)[0];return {position,name,meaning,energy,imageUrl:commons(file)}})}

const initials=['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];
const initialStrokes=[2,4,2,3,6,5,4,4,8,2,4,1,3,6,4,2,4,4,3],vowelStrokes=[2,3,3,4,2,3,3,4,2,3,4,3,4,3,4,4,4,3,3,3,4],finalStrokes=[0,2,4,4,2,5,5,7,4,6,8,8,2,4,4,1,3,4,6,2,4,1,3,4,3,4,4,3];
const elementFor=(j:string)=>'ㄱㅋ'.includes(j)?'목':'ㄴㄷㄹㅌ'.includes(j)?'화':'ㅁㅂㅍ'.includes(j)?'수':'ㅅㅈㅊ'.includes(j)?'금':'토';
function readName(name:string){let strokeTotal=0,yin=0,yang=0;const elements:string[]=[];for(const char of name.replace(/\s/g,'')){const code=char.charCodeAt(0)-0xac00;if(code>=0&&code<11172){const cho=Math.floor(code/588),jung=Math.floor((code%588)/28),jong=code%28,s=initialStrokes[cho]+vowelStrokes[jung]+finalStrokes[jong];strokeTotal+=s;s%2?yang++:yin++;elements.push(elementFor(initials[cho]));}else strokeTotal+=char.codePointAt(0)!%9+1;}const counts=elements.reduce<Record<string,number>>((m,e)=>(m[e]=(m[e]||0)+1,m),{}),primaryElement=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'토';return {name,strokeTotal,number:strokeTotal%9||9,yin,yang,primaryElement,elements};}
const generates:Record<string,string>={목:'화',화:'토',토:'금',금:'수',수:'목'};
const controls:Record<string,string>={목:'토',토:'수',수:'화',화:'금',금:'목'};
const relationCycle=[-12,-6,2,8,14,-10,-2,6,12,-8];
function nameCompatibility(a:ReturnType<typeof readName>,b:ReturnType<typeof readName>){const same=a.primaryElement===b.primaryElement,generating=generates[a.primaryElement]===b.primaryElement||generates[b.primaryElement]===a.primaryElement,controlling=controls[a.primaryElement]===b.primaryElement||controls[b.primaryElement]===a.primaryElement,element=same?6:generating?14:controlling?-14:-4,number=12-Math.abs(a.number-b.number)*3,balance=8-Math.abs((a.yang-a.yin)-(b.yang-b.yin))*4,cycle=relationCycle[(a.strokeTotal+b.strokeTotal)%10];return Math.max(24,Math.min(94,49+element+number+balance+cycle));}
function build(a:string,b:string,tarot:ReturnType<typeof drawTarot>){
  const ra=readName(a),rb=readName(b),nameScore=nameCompatibility(ra,rb);
  const same=ra.primaryElement===rb.primaryElement,flows=generates[ra.primaryElement]===rb.primaryElement||generates[rb.primaryElement]===ra.primaryElement,clashes=controls[ra.primaryElement]===rb.primaryElement||controls[rb.primaryElement]===ra.primaryElement;
  const elementFit=same?70:flows?88:clashes?28:52,numberFit=Math.max(20,92-Math.abs(ra.number-rb.number)*9),balanceFit=Math.max(25,90-Math.abs((ra.yang-ra.yin)-(rb.yang-rb.yin))*15);
  const current=tarot[0].energy,attraction=tarot[1].energy,future=tarot[2].energy,tarotScore=Math.round((current+attraction+future)/3),overall=Math.max(20,Math.min(97,Math.round(nameScore*.85+tarotScore*.15)));
  const closenessPotential=Math.round(elementFit*.45+attraction*.35+numberFit*.2),relationshipStability=Math.round(numberFit*.35+balanceFit*.35+future*.3),conversationCompatibility=Math.round(balanceFit*.55+elementFit*.3+current*.15),mutualAwareness=Math.round(attraction*.7+elementFit*.3),comfortPotential=Math.round(elementFit*.4+balanceFit*.4+current*.2);
  const awkwardnessRisk=100-closenessPotential,misunderstandingRisk=100-conversationCompatibility,communicationDropRisk=100-relationshipStability,conflictRisk=Math.round((100-elementFit)*.55+(100-balanceFit)*.45),distancingRisk=Math.round((100-relationshipStability)*.65+(100-future)*.35);
  const cards=tarot.map(({position,name,meaning,imageUrl})=>({position,name,meaning,imageUrl})),flowText=flows?'상생 관계라 한쪽의 기운이 다른 쪽으로 자연스럽게 이어져요':clashes?'상극 관계라 끌림과 별개로 반응 방식이 부딪힐 수 있어요':same?'같은 오행이라 익숙함은 빠르지만 고집도 닮을 수 있어요':'직접적인 상생·상극은 아닌 중간 관계예요';
  const positiveFactors=[`${a}님의 ${ra.primaryElement} 기운과 ${b}님의 ${rb.primaryElement} 기운은 ${flowText} 오행 조화도는 ${elementFit}%로 계산됐어요.`,`두 이름의 총획은 ${ra.strokeTotal}획과 ${rb.strokeTotal}획, 수리는 ${ra.number}와 ${rb.number}예요. 수리 차이를 반영한 획수 조화도는 ${numberFit}%입니다.`,`끌림 자리에 나온 ‘${cards[1].name}’ 카드는 ${cards[1].meaning}을 뜻해요. 이 카드의 전통적 에너지와 오행을 합친 서로 의식하는 정도는 ${mutualAwareness}%예요.`];
  const cautionFactors=[`음양 구성은 ${a}님이 음 ${ra.yin}·양 ${ra.yang}, ${b}님이 음 ${rb.yin}·양 ${rb.yang}이에요. 균형도 ${balanceFit}%를 바탕으로 오해 가능성을 ${misunderstandingRisk}%로 계산했어요.`,`현재 자리에 나온 ‘${cards[0].name}’은 ${cards[0].meaning}을 나타냅니다. 오행과 음양까지 합치면 갈등 신호는 ${conflictRisk}%라서 감정이 올라올 때 단정하지 않는 편이 좋아요.`,`앞으로의 자리에 나온 ‘${cards[2].name}’은 ${cards[2].meaning}의 흐름이에요. 수리 안정도와 카드 에너지를 합친 멀어질 가능성은 ${distancingRisk}%입니다.`];
  return {overallCompatibility:overall,closenessPotential,relationshipStability,conversationCompatibility,mutualAwareness,comfortPotential,awkwardnessRisk,misunderstandingRisk,communicationDropRisk,conflictRisk,distancingRisk,tarotCards:cards,nameReadings:[ra,rb],nameMethod:'현대 한글 자형 획수의 홀짝을 음양으로 보고, 첫소리의 발음오행·상생과 상극·총획 수리를 비교했어요. 이름 계산 85%, 타로 15%를 반영하며 각 세부 수치는 같은 요소에서 직접 산출해요.',summary:`${a}님의 이름은 ${ra.strokeTotal}획·${ra.primaryElement} 기운, ${b}님의 이름은 ${rb.strokeTotal}획·${rb.primaryElement} 기운으로 읽혀요. 두 이름의 성명학 점수는 ${nameScore}점이고 ${flowText} 현재의 ‘${cards[0].name}’, 끌림의 ‘${cards[1].name}’, 미래의 ‘${cards[2].name}’을 함께 반영한 최종 점수는 ${overall}점입니다. ${overall<50?'이 조합은 호감이 있어도 오행과 음양의 반응 차이가 커서, 추측보다 직접 확인하는 태도가 중요해요.':overall<70?'완벽하게 맞는 관계라기보다 서로 다른 반응을 이해하면서 안정되는 관계예요.':'이름의 흐름과 카드의 방향이 비교적 잘 이어지지만, 좋은 궁합도 솔직한 표현이 있어야 유지돼요.'}`,positiveFactors,cautionFactors};
}

async function activity(names:string[]=[]){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!pub)return {runCount:78,popularNames:[] as string[]};const db=createClient(url,pub,{auth:{persistSession:false}}),{data,error}=await db.rpc('get_activity_snapshot',{input_names:names.slice(0,2)});if(error){console.error('activity',error.code);return {runCount:78,popularNames:[] as string[]}}const row=Array.isArray(data)?data[0]:null;return {runCount:Number(row?.run_count)||78,popularNames:Array.isArray(row?.popular_names)?row.popular_names:[] as string[]}}
export async function GET(){return NextResponse.json({activity:await activity()})}
export async function POST(req:Request){try{const v=input.parse(await req.json()),parsed=output.parse(build(v.nameA,v.nameB,drawTarot())),url=process.env.NEXT_PUBLIC_SUPABASE_URL,pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(url&&pub){const db=createClient(url,pub,{auth:{persistSession:false}});const {error}=await db.from('analysis_submissions').insert({name_a:v.nameA,gender_a:v.genderA,name_b:v.nameB,gender_b:v.genderB,overall_score:parsed.overallCompatibility,analysis_result:parsed});if(error)console.error('storage',error.code)}return NextResponse.json({result:parsed,activity:await activity([v.nameA,v.nameB]),engine:'name-numerology-tarot'});}catch(e){console.error(e);return NextResponse.json({error:'분석을 완료하지 못했어요. 한글 이름을 확인하고 잠시 후 다시 시도해 주세요.'},{status:400})}}
