import { randomInt } from 'node:crypto';
import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';

export const runtime = 'nodejs';
const input=z.object({nameA:z.string().trim().min(1).max(20).regex(/^[\p{L}\p{M}\s'-]+$/u),nameB:z.string().trim().min(1).max(20).regex(/^[\p{L}\p{M}\s'-]+$/u),genderA:z.enum(['male','female','unspecified']),genderB:z.enum(['male','female','unspecified'])});
const tarotCard=z.object({position:z.string(),name:z.string(),meaning:z.string(),imageUrl:z.string().url()});
const nameReading=z.object({name:z.string(),strokeTotal:z.number(),number:z.number(),yin:z.number(),yang:z.number(),primaryElement:z.string(),elements:z.array(z.string())});
const output=z.object({overallCompatibility:z.number().min(0).max(100),closenessPotential:z.number().min(0).max(100),relationshipStability:z.number().min(0).max(100),conversationCompatibility:z.number().min(0).max(100),mutualAwareness:z.number().min(0).max(100),comfortPotential:z.number().min(0).max(100),awkwardnessRisk:z.number().min(0).max(100),misunderstandingRisk:z.number().min(0).max(100),communicationDropRisk:z.number().min(0).max(100),conflictRisk:z.number().min(0).max(100),distancingRisk:z.number().min(0).max(100),summary:z.string().min(30).max(1000),tarotCards:z.array(tarotCard).length(3),nameReadings:z.array(nameReading).length(2),nameMethod:z.string(),positiveFactors:z.array(z.string()).min(3).max(4),cautionFactors:z.array(z.string()).min(3).max(4),relationshipAdvice:z.array(z.string()).min(3).max(4)});

const commons=(file:string)=>`https://commons.wikimedia.org/wiki/Special:Redirect/file/${file}`;
const deck=[
['바보','새로운 시작, 솔직한 호기심',72,'RWS_Tarot_00_Fool.jpg'],['마법사','먼저 다가가는 힘, 강한 표현력',84,'RWS_Tarot_01_Magician.jpg'],['여사제','말하지 않아도 느끼는 직감',78,'RWS_Tarot_02_High_Priestess.jpg'],['여황제','다정함, 편안한 애정',90,'RWS_Tarot_03_Empress.jpg'],['황제','안정감, 관계의 주도권',76,'RWS_Tarot_04_Emperor.jpg'],['교황','신뢰, 약속을 지키는 마음',82,'RWS_Tarot_05_Hierophant.jpg'],['연인','끌림, 중요한 선택',94,'RWS_Tarot_06_Lovers.jpg'],['전차','빠른 진전, 같은 목표',86,'RWS_Tarot_07_Chariot.jpg'],['힘','부드러운 인내, 감정 조절',88,'RWS_Tarot_08_Strength.jpg'],['은둔자','천천히 알아가는 시간',62,'RWS_Tarot_09_Hermit.jpg'],['운명의 수레바퀴','예상 밖의 만남과 변화',83,'RWS_Tarot_10_Wheel_of_Fortune.jpg'],['정의','솔직한 대화, 균형',80,'RWS_Tarot_11_Justice.jpg'],['매달린 사람','기다림, 관점 바꾸기',60,'RWS_Tarot_12_Hanged_Man.jpg'],['죽음','묵은 흐름의 끝과 새 출발',68,'RWS_Tarot_13_Death.jpg'],['절제','서로 다른 속도를 맞추는 힘',87,'RWS_Tarot_14_Temperance.jpg'],['악마','강한 끌림, 집착을 조심할 필요',65,'RWS_Tarot_15_Devil.jpg'],['탑','갑작스러운 감정 변화와 깨달음',55,'RWS_Tarot_16_Tower.jpg'],['별','기대, 오래 남는 설렘',92,'RWS_Tarot_17_Star.jpg'],['달','헷갈리는 신호, 깊은 감정',64,'RWS_Tarot_18_Moon.jpg'],['태양','함께 있을 때 커지는 밝은 에너지',96,'RWS_Tarot_19_Sun.jpg'],['심판','다시 이어지는 대화, 중요한 결론',81,'RWS_Tarot_20_Judgement.jpg'],['세계','잘 맞물리는 흐름, 완성감',95,'RWS_Tarot_21_World.jpg']] as const;
const positions=['지금 두 사람의 흐름','서로 끌리는 이유','앞으로의 방향'];
function drawTarot(){const pool=[...deck];return positions.map(position=>{const [name,meaning,energy,file]=pool.splice(randomInt(pool.length),1)[0];return {position,name,meaning,energy,imageUrl:commons(file)}})}

const initials=['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];
const initialStrokes=[2,4,2,3,6,5,4,4,8,2,4,1,3,6,4,2,4,4,3],vowelStrokes=[2,3,3,4,2,3,3,4,2,3,4,3,4,3,4,4,4,3,3,3,4],finalStrokes=[0,2,4,4,2,5,5,7,4,6,8,8,2,4,4,1,3,4,6,2,4,1,3,4,3,4,4,3];
const elementFor=(j:string)=>'ㄱㅋ'.includes(j)?'목':'ㄴㄷㄹㅌ'.includes(j)?'화':'ㅁㅂㅍ'.includes(j)?'수':'ㅅㅈㅊ'.includes(j)?'금':'토';
function readName(name:string){let strokeTotal=0,yin=0,yang=0;const elements:string[]=[];for(const char of name.replace(/\s/g,'')){const code=char.charCodeAt(0)-0xac00;if(code>=0&&code<11172){const cho=Math.floor(code/588),jung=Math.floor((code%588)/28),jong=code%28,s=initialStrokes[cho]+vowelStrokes[jung]+finalStrokes[jong];strokeTotal+=s;s%2?yang++:yin++;elements.push(elementFor(initials[cho]));}else strokeTotal+=char.codePointAt(0)!%9+1;}const counts=elements.reduce<Record<string,number>>((m,e)=>(m[e]=(m[e]||0)+1,m),{}),primaryElement=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'토';return {name,strokeTotal,number:strokeTotal%9||9,yin,yang,primaryElement,elements};}
const generates:Record<string,string>={목:'화',화:'토',토:'금',금:'수',수:'목'};
function nameCompatibility(a:ReturnType<typeof readName>,b:ReturnType<typeof readName>){const element=a.primaryElement===b.primaryElement?13:generates[a.primaryElement]===b.primaryElement||generates[b.primaryElement]===a.primaryElement?18:7,number=20-Math.abs(a.number-b.number)*2,balance=18-Math.abs((a.yang-a.yin)-(b.yang-b.yin))*2;return Math.max(42,Math.min(96,42+element+number+balance));}
function pick<T>(items:T[],count=3){const pool=[...items],picked:T[]=[];while(picked.length<count&&pool.length)picked.push(pool.splice(randomInt(pool.length),1)[0]);return picked}
const positives=['발음오행의 흐름이 서로의 부족한 기운을 채워 줘요','두 이름의 수리가 가까워 대화 속도를 맞추기 쉬워요','음과 양의 비율이 관계에 적당한 긴장감과 편안함을 만들어요','타로 흐름상 먼저 말을 걸었을 때 반응이 좋은 조합이에요','서로 다른 오행이 새로운 매력으로 느껴질 수 있어요','작은 공통점을 빠르게 찾아 친해지기 쉬운 이름 조합이에요'];
const cautions=['오행의 속도가 달라 한쪽이 너무 빨리 결론을 내리지 않는 게 좋아요','답장이 늦을 때 혼자 의미를 크게 만들지 않는 게 좋아요','음양의 반응 차이 때문에 장난을 진심으로 받아들일 수 있어요','서로 눈치를 보다 중요한 말을 미룰 수 있어요','강한 타로 카드가 나온 만큼 질투나 집착은 바로 말로 풀어야 해요','주변 친구들의 말보다 두 사람이 직접 확인하는 게 중요해요'];
const advices=['상대 이름의 부족한 오행을 상징하는 색이나 장소로 약속을 잡아 보세요','좋아하는 노래나 영상을 하나씩 주고받아 보세요','애매한 표현 대신 보고 싶다거나 서운했다고 짧게 말해 보세요','둘만 알아듣는 작은 농담을 만들어 보세요','짧게라도 다음에 만날 약속을 구체적으로 잡아 보세요','상대가 잘한 일을 발견하면 바로 말해 주세요'];
function build(a:string,b:string,tarot:ReturnType<typeof drawTarot>){const ra=readName(a),rb=readName(b),nameScore=nameCompatibility(ra,rb),tarotScore=Math.round(tarot.reduce((s,c)=>s+c.energy,0)/3),overall=Math.round(nameScore*.7+tarotScore*.3),vary=(base:number,spread=12)=>Math.max(8,Math.min(97,Math.round(base)+randomInt(-spread,spread+1))),cards=tarot.map(({position,name,meaning,imageUrl})=>({position,name,meaning,imageUrl})),flows=generates[ra.primaryElement]===rb.primaryElement||generates[rb.primaryElement]===ra.primaryElement;return {overallCompatibility:overall,closenessPotential:vary(overall),relationshipStability:vary(nameScore),conversationCompatibility:vary((nameScore+tarotScore)/2),mutualAwareness:vary(tarotScore),comfortPotential:vary(overall),awkwardnessRisk:vary(100-overall,10),misunderstandingRisk:vary(100-nameScore,14),communicationDropRisk:vary(100-overall,16),conflictRisk:vary(100-nameScore,12),distancingRisk:vary(100-overall,10),tarotCards:cards,nameReadings:[ra,rb],nameMethod:'현대 한글 자형 획수의 홀짝을 음양으로 보고, 첫소리의 발음오행과 총획 수리를 함께 비교했어요.',summary:`${a}님의 이름은 ${ra.strokeTotal}획·${ra.primaryElement} 기운, ${b}님의 이름은 ${rb.strokeTotal}획·${rb.primaryElement} 기운으로 읽혀요. 두 이름의 수리 궁합은 ${nameScore}점이며, ${flows?'서로의 오행이 자연스럽게 이어지는 상생 흐름이 보여요':'같은 점보다 서로 다른 반응을 이해할수록 좋아지는 흐름이에요'}. 타로에서는 ‘${cards[0].name}’이 현재를, ‘${cards[1].name}’이 끌림의 이유를, ‘${cards[2].name}’이 앞으로의 방향을 보여 줍니다. 이름 계산값과 카드 흐름을 함께 보면 사소한 대화 하나가 관계의 분위기를 크게 바꿀 수 있는 조합이에요.`,positiveFactors:pick(positives),cautionFactors:pick(cautions),relationshipAdvice:pick(advices)};}

async function activity(names:string[]=[]){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!pub)return {runCount:78,popularNames:[] as string[]};const db=createClient(url,pub,{auth:{persistSession:false}}),{data,error}=await db.rpc('get_activity_snapshot',{input_names:names.slice(0,2)});if(error){console.error('activity',error.code);return {runCount:78,popularNames:[] as string[]}}const row=Array.isArray(data)?data[0]:null;return {runCount:Number(row?.run_count)||78,popularNames:Array.isArray(row?.popular_names)?row.popular_names:[] as string[]}}
export async function GET(){return NextResponse.json({activity:await activity()})}
export async function POST(req:Request){try{const v=input.parse(await req.json()),parsed=output.parse(build(v.nameA,v.nameB,drawTarot())),url=process.env.NEXT_PUBLIC_SUPABASE_URL,pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(url&&pub){const db=createClient(url,pub,{auth:{persistSession:false}});const {error}=await db.from('analysis_submissions').insert({name_a:v.nameA,gender_a:v.genderA,name_b:v.nameB,gender_b:v.genderB,overall_score:parsed.overallCompatibility,analysis_result:parsed});if(error)console.error('storage',error.code)}return NextResponse.json({result:parsed,activity:await activity([v.nameA,v.nameB]),engine:'name-numerology-tarot'});}catch(e){console.error(e);return NextResponse.json({error:'분석을 완료하지 못했어요. 한글 이름을 확인하고 잠시 후 다시 시도해 주세요.'},{status:400})}}
