import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';
export const runtime='nodejs';
const input=z.object({nameA:z.string().trim().min(1).max(20).regex(/^[\p{L}\p{M}\s'-]+$/u),nameB:z.string().trim().min(1).max(20).regex(/^[\p{L}\p{M}\s'-]+$/u),genderA:z.enum(['male','female','unspecified']),genderB:z.enum(['male','female','unspecified'])});
const output=z.object({overallCompatibility:z.number().min(0).max(100),closenessPotential:z.number().min(0).max(100),relationshipStability:z.number().min(0).max(100),conversationCompatibility:z.number().min(0).max(100),mutualAwareness:z.number().min(0).max(100),comfortPotential:z.number().min(0).max(100),awkwardnessRisk:z.number().min(0).max(100),misunderstandingRisk:z.number().min(0).max(100),communicationDropRisk:z.number().min(0).max(100),conflictRisk:z.number().min(0).max(100),distancingRisk:z.number().min(0).max(100),summary:z.string().min(30).max(600),positiveFactors:z.array(z.string()).min(2).max(4),cautionFactors:z.array(z.string()).min(2).max(4),relationshipAdvice:z.array(z.string()).min(2).max(4)});
function seeded(a:string,b:string){let h=2166136261;for(const c of a+'|'+b){h^=c.codePointAt(0)||0;h=Math.imul(h,16777619)}return()=>((h=Math.imul(h^h>>>15,1|h))>>>0)/4294967295}
function fallback(a:string,b:string){const r=seeded(a,b),n=(l:number,h:number)=>Math.round(l+r()*(h-l)),overall=n(58,94);return {overallCompatibility:overall,closenessPotential:n(55,96),relationshipStability:n(50,93),conversationCompatibility:n(52,96),mutualAwareness:n(48,95),comfortPotential:n(54,96),awkwardnessRisk:n(12,55),misunderstandingRisk:n(18,58),communicationDropRisk:n(12,52),conflictRisk:n(10,48),distancingRisk:n(10,46),summary:`${a}님과 ${b}님의 이름 흐름에는 서로 다른 결을 자연스럽게 연결하는 힘이 보여요. 처음에는 표현 방식의 차이가 느껴질 수 있지만, 대화를 이어 갈수록 서로의 장점을 빠르게 알아보는 관계입니다.`,positiveFactors:['서로의 분위기를 편안하게 만드는 흐름','대화 속에서 공통점을 발견하는 힘','필요할 때 균형을 잡아 주는 조합'],cautionFactors:['답을 재촉하면 작은 오해가 생길 수 있어요','감정을 혼자 정리하다 연락이 뜸해질 수 있어요'],relationshipAdvice:['추측보다 짧고 솔직한 질문을 건네 보세요','좋았던 순간을 구체적으로 표현해 주세요','각자의 속도를 존중하면 관계가 더 단단해져요']}}
async function activity(names:string[]=[]){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!pub)return {runCount:78,popularNames:[] as string[]};const db=createClient(url,pub,{auth:{persistSession:false}}),{data,error}=await db.rpc('get_activity_snapshot',{input_names:names.slice(0,2)});if(error){console.error('activity',error.code);return {runCount:78,popularNames:[] as string[]}}const row=Array.isArray(data)?data[0]:null;return {runCount:Number(row?.run_count)||78,popularNames:Array.isArray(row?.popular_names)?row.popular_names:[] as string[]}}
export async function GET(){return NextResponse.json({activity:await activity()})}
export async function POST(req:Request){try{const v=input.parse(await req.json());let result:unknown;const aiKey=process.env.AI_GATEWAY_API_KEY;if(aiKey){const res=await fetch('https://ai-gateway.vercel.sh/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${aiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.AI_MODEL||'openai/gpt-5-mini',response_format:{type:'json_object'},temperature:.8,messages:[{role:'system',content:'한국어 관계 궁합 해석가로서 과학적 사실처럼 단정하지 않고 오락용 이름 궁합을 작성한다. 장점과 주의점을 균형 있게 포함하고 요청 스키마와 같은 JSON만 반환한다.'},{role:'user',content:JSON.stringify(v)}]})});if(!res.ok)throw new Error('AI 요청 실패');const d=await res.json();result=JSON.parse(d.choices?.[0]?.message?.content||'{}')}else result=fallback(v.nameA,v.nameB);const parsed=output.parse(result);const url=process.env.NEXT_PUBLIC_SUPABASE_URL,pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(url&&pub){const db=createClient(url,pub,{auth:{persistSession:false}});const {error}=await db.from('analysis_submissions').insert({name_a:v.nameA,gender_a:v.genderA,name_b:v.nameB,gender_b:v.genderB,overall_score:parsed.overallCompatibility,analysis_result:parsed});if(error)console.error('storage',error.code)}return NextResponse.json({result:parsed,activity:await activity([v.nameA,v.nameB]),engine:aiKey?'ai':'demo'});}catch(e){console.error(e);return NextResponse.json({error:'분석을 완료하지 못했어요. 이름을 확인하고 잠시 후 다시 시도해 주세요.'},{status:400})}}
